# Generated by Django 4.1.5 on 2023-04-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_center_remove_student_branch_delete_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.center'),
        ),
    ]
