# Generated by Django 4.1.5 on 2023-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_coordinator_center_coordinator_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_Name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_Devision',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_Standard',
            field=models.IntegerField(null=True),
        ),
    ]
