# Generated by Django 4.1.5 on 2023-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_student_school_address_student_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age_group',
            field=models.CharField(choices=[('1-14', '1-14'), ('15-25', '15-25')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_Devision',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
