# Generated by Django 4.1.5 on 2023-04-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_student_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_proof2',
            field=models.ImageField(default='', upload_to='id_proof2/'),
        ),
    ]
