# Generated by Django 4.1.5 on 2023-04-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_student_id_proof2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_proof2',
        ),
    ]
