# Generated by Django 4.1.5 on 2023-04-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_timesection_attends_center_timesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='timesection',
        ),
        migrations.AddField(
            model_name='timesection',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.center'),
        ),
    ]
