# Generated by Django 4.2 on 2023-04-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_remove_center_timesection_timesection_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attends',
        ),
    ]
