# Generated by Django 4.2 on 2023-04-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_student_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_date',
        ),
    ]
