# Generated by Django 4.2 on 2023-04-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_rename_batch_name_batch_name_remove_batch_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesection',
            name='center',
        ),
        migrations.AddField(
            model_name='timesection',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch'),
        ),
    ]
