# Generated by Django 4.2 on 2023-04-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_remove_timesection_center_timesection_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('lead_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Other', 'Other')], max_length=100)),
                ('lead_status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Success', 'Success')], default='Pending', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.coordinator')),
            ],
        ),
    ]
